### ISSUE TITLE
Unable to require with NodeJS testing

### ISSUE THREAD

**Issue by mbenjamin618** [wmcmahan/react-native-calendar-events#33] opened 2016-12-28 18:27 UTC
When trying to run a test I receive the Error:

"Cannot find module 'react-native-calendar-events'"

I believe the reason for this error is there is no main file specified in package.json and the normal require resolver does not know how to handle index.ios.js vs index.android.js.

**Comment by wmcmahan** [comment] 2016-12-30 13:36
@mbenjamin618 Yeah, a single, non-platform specific entry might be better for this package anyway. I will look into resolving this. Thanks

**Comment by JonathonJulian** [comment] 2017-01-05 18:35
my  linter was also complain about this, i had to use the absolute path to the js file for my platform

**Comment by mtt87** [comment] 2017-01-27 14:34
If the problem is related to ESlint you can fix adding this to `.eslintrc`
```
	"settings": {
		"import/resolver": {
			"node": {
				"extensions": [
					".js",
					".android.js",
					".ios.js"
				]
			}
		}
	},
```

**Closed** 2017-08-24 13:01 UTC
