### ISSUE TITLE
fetchAll and recurring events in Android

### ISSUE THREAD

**Issue by franleplant** [wmcmahan/react-native-calendar-events#44] opened 2017-02-09 14:54 UTC
Hi! Thanks a lot for your library.

I've double checked this behavior in at least two android devices.

Expected: `fetchAll` should fetch all events in all calendars
Actual: `fetchAll` is not fetching the recurrent events in all calendars

It fetches correctly all events but recurring ones.

Is there something am I missing or is this an actual bug?

Thanks a lot!
Fran

**Comment by wmcmahan** [comment] 2017-02-09 16:29
Hey @franleplant, I believe that this is expected for Android when reading from the [CalendarContract.Event](https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java#L132-L162) table. I think that reading from the `CalendarContract.Instances` would successfully find all instances from the query. The current response should return a recurrent rule that could be used to infer future dates without a pulling every instance though.

**Comment by franleplant** [comment] 2017-02-09 16:38
So right now I am not receiving those events from `fetchAll`, what is your suggestion to fix this then?

**Comment by wmcmahan** [comment] 2017-02-09 19:21
Just to clarify, the results are all non recurring events, i.e. nothing assigned to the `recurrence` key such as 'daily', 'weekly', etc?

**Comment by franleplant** [comment] 2017-02-13 14:03
Exactly, the `recurrence` key is always the empty string and the events are all non-recurrent. Other way of putting it is that `fetchAll` is not returning instances of recurrent events.

**Comment by wmcmahan** [comment] 2017-02-13 14:27
Hey @franleplant, I'm not able to reproduce this. Can you show how you are creating a recurring event and how you are fetching these events?

**Comment by franleplant** [comment] 2017-02-13 17:06
Hi! This is all the data I could gather:


This is a recurring event that happens every Wednesday (I've omitted some details for privacy reasons)

![screenshot_20170213-130525 1](https://cloud.githubusercontent.com/assets/1852455/22893635/ffba9c34-f1f4-11e6-8729-dfd5cc99bba1.png)
 
![screenshot_20170213-130952](https://cloud.githubusercontent.com/assets/1852455/22893646/0b068d46-f1f5-11e6-9ff6-7dea34afd978.png)

This is the code that fetches all the events for today, tomorrow and the day past tomorrow and store them
in an array.

```javascript
  const events = await Promise.all([0, 1, 2]
   // Calc the start and end of (today, tomorrow or the day after tomorrow) in the user's timezone
        .map((i) => [moment().startOf('day').add(i, "day"), moment().endOf('day').add(i, "day")])
        // Get events
        .map(([start, end]) => RNCalendarEvents.fetchAllEvents(start.toISOString(), end.toISOString())))
```

This is what I get from that call
![screen shot 2017-02-13 at 1 59 09 pm](https://cloud.githubusercontent.com/assets/1852455/22893688/37269e70-f1f5-11e6-979f-d4da9d27d874.png)

The event that you see on Wednesday is other, non recurring event, that in fact comes from another calendar that I'm subscribed too, so that's working fine. The only problem is for recurring events.

I hope this helps.

A simple way of reproducing this error is by:
- create a non recurring event A today
- create a recurring event B today (potentially start it yesterday so you get a future recurring event)
- run `fetchAll` for today
- Only A will be present in the events Array.

Expected: A and B are returned
Actual: A is returned

**Comment by wmcmahan** [comment] 2017-02-13 17:37
Thanks @franleplant, I believe I see what the problem is. Recurring events (without an end date) cannot be found by the queries start and end date bounds. I should have a solution out for this later today. Thanks for reporting it!

**Comment by wmcmahan** [comment] 2017-02-13 18:14
Ok, i've pushed out a patch (1.3.5) for this. Hopefully this should now pull recurring events properly. Let me know if you run into any bugs. Cheers!

**Closed by wmcmahan** 2017-02-13 18:14 UTC

**Comment by franleplant** [comment] 2017-02-13 19:33
Thank you very much for your help and support!

**Comment by wmcmahan** [comment] 2017-02-13 21:31
Glad I could help. 👍
