### ISSUE TITLE
events found using RNCalendarEvents.fetchAllEvents are not in sync with the system calendar.

### ISSUE THREAD

**Issue by ConnectedReasoning** [wmcmahan/react-native-calendar-events#260] opened 2019-07-18 12:37 UTC
It appears that the events found using RNCalendarEvents.fetchAllEvents are not in sync with the system calendar.

### Environment
* Mac iOS development using simulator
* Visual Studio code editor, 
* x-code simulator, 
* react -v 16.8.3
* react-native -v 0.59.2
* react-native-calendar-events - 1.7.3

### Steps to Reproduce
* run an app using react-native -calendar-events 
* create a calendar 
* add items to calendar using react-native-calendar-events
* run MacOS calendar application add calendar events to same calendar your iOS app uses
* run app and  get a list of all events in your calendar (im using moment in this example

~~~~

    const findCalendarsPromise = RNCalendarEvents.findCalendars()
    findCalendarPromise.then(calendars =>{
      const myCalendars = calendars.filter(calendar =>{
        return calendar.title === 'thisAppsCalendar';
      });
      console.log('myCalendars is ', myCalendars);
      let fetchCalendarEventsPromise = RNCalendarEvents.fetchAllEvents('2019-06-02T17:24:00.000Z', '2019-09-02T17:24:00.000Z,' [myCalendars[0].id]);
      fetchCalendareventsPromise.then(events =>{
        console.log('fetchCalendareventsPromise success result is ', events);
      });
    }).catch(error =>{
      console.log(error)
    });

~~~~

### Expected Behavior
I expect to see system calendar events match the events found using fetchAllEvents
### Actual Behavior
The events I retrieve using fetchAllEvents do not contain items I added outside of react-native-calendar-events.

**Comment by ConnectedReasoning** [comment] 2019-07-18 13:01
One thing I notice is that the keys used between RNCalendarEvents and my system calendars are different. Are the calendars stored in a cache?

**Comment by ConnectedReasoning** [comment] 2019-09-19 14:34
Am I the only person experiencing this? I think I may need to write a swift external method to handle but I would rather use react-native-calendar-events

**Comment by jdegger** [comment] 2019-10-03 14:11
I'm also seeing this behavior. Did you solve it? Working fine on iOS but on Android I'm just not seeing any results.

**Comment by ConnectedReasoning** [comment] 2019-11-11 01:00
I never did solve it. I put using it on hold and implemented an internal calendar, but I sure would like to use the device native calendars instead. I will try again soon.

**Comment by jdegger** [comment] 2019-11-11 07:37
We solved it in our fork, however we also changed some of the behaviour to fit our own use cases. 

You'd have to selectively pick the commits on this repo to fix the problem.

https://github.com/X-Guard/react-native-calendar-events/commits/master

**Comment by mukeshsharma1201** [comment] 2019-12-13 09:18
Facing the same issue on both iOS and Android.

**Comment by MoOx** [comment] 2020-04-24 10:22
@jdegger I have been added as a maintainer and would love to make this package more stable & complete. Feel free to make a PR so we can improve this here!

**Comment by jdegger** [comment] 2020-04-24 10:26
@MoOx we don't have time to create the PR at the moment sorry.

However, I have selected the relevant commits for you to maybe take over or look at:
- https://github.com/X-Guard/react-native-calendar-events/commit/8d23ef62b63b9f1f44a967ddd6afe34b8cc6173e
- https://github.com/X-Guard/react-native-calendar-events/commit/612bba15eb228ccf6c6eac634569d78af4796857
- https://github.com/X-Guard/react-native-calendar-events/commit/612bba15eb228ccf6c6eac634569d78af4796857#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R4

**Comment by sunwooz** [comment] 2020-09-15 14:58
@MoOx Has this been fixed yet on any of the newer versions?

**Comment by MoOx** [comment] 2020-09-15 15:05
I didn't see how the commits mentioned above resolve the issue as they seems to adresse a "lite" version (just #251)...
Please have a look in the changelog, but I think I didn't merge anything related to this issue (I am for now actively working with this lib, mostly on iOS, so I am not a good android user (yet))

**Comment by shasankm** [comment] 2020-09-26 19:02
You need to sync your calendar events under Settings > Account (Google) to see the *latest* changes.

**Comment by MoOx** [comment] 2020-12-05 16:42
This might be a sync problem (see https://github.com/wmcmahan/react-native-calendar-events#troubleshooting). Without more information or an easy way to reproduce 100% of the time, we cannot help that much.
Please check that the OS have synced all events before trying to access the API of this module that just access local devices data. If data on the device is not synced, the API cannot request a data update.

I have no idea if that's possible yet (I will have this need one day or another but for now I just expect the device to be up to date).

During development, your devices are not always up to date because you expect things to be available right away, when they are not. In real life, sync is probably happening enough time so your app can expect to have "all events". Closing for now. We can still continue to discuss but I don't think there is a bug for now according to the behaviour of this lib.

**Closed by MoOx** 2020-12-05 16:42 UTC
