### ISSUE TITLE
fectchAll doesn't return all events

### ISSUE THREAD

**Issue by geohuz** [wmcmahan/react-native-calendar-events#2] opened 2016-03-04 13:37 UTC
On my macbookpro I have my calendars setup to sync to a remote caldav server, and I can see a whole list of full year's events on the calendar upon successfully setup. And then I wrote the following code in my react-native dev project:

```
    componentDidMount() {
      RNCalendarEvents.fetchAllEvents('2016-01-01T00:00:00.000Z', 
                                      '2016-12-30T23:00:00.000Z', 
                                      events => {
                                        console.log(events)
                                      }
                                    )
    }
```

But I only see 4 items which are synced with my friends birthday found in the email. Is there anyway I can do with this issue?

**Comment by wmcmahan** [comment] 2016-03-04 20:21
The fetch method should be searching in all available calendars on an IOS device. I've only tested with a google account and was able to successfully fetch events synced through google. My only thought is that either they didn't fully sync or something is off in the devices calendar settings. I will keep looking to see if I can reproduce.

**Comment by geohuz** [comment] 2016-03-05 04:22
I was wondering if the fetchAllevents would be changed to promise as described in the facebook document, something like this:

```
RCT_REMAP_METHOD(findEvents,
                 resolver:(RCTPromiseResolveBlock)resolve
                 rejecter:(RCTPromiseRejectBlock)reject)
{
  NSArray *events = ...
  if (events) {
    resolve(events);
  } else {
    NSError *error = ...
    reject(@"no_events", @"There were no events", error);
  }
}
```

As my calendar has hundred events through the year, it takes time to fetch them all?

**Comment by wmcmahan** [comment] 2016-03-05 15:40
Cool, I had not seen this macro. IOS's method to access events is `eventsMatchingPredicate`, which is synchronous and therefore run in another thread. With a large time range and hundreds of events, it will always take time to find events in the store. Unfortunately, using a promise or callback won't make the lookup an faster. Are you experiencing the main thread getting blocked?

I do like the idea of promises for this though. It could make for some cleaner code.

**Comment by geohuz** [comment] 2016-03-07 04:48
Actually I can't set the events property during the startup, here is my code:

```
class mobileCalendar extends Component{
    constructor(props) {
      super(props);
      this.state = {
        cEvents: null
      };
    }
    
    componentWillMount() {
      //this.fetchData()
    }

    componentDidMount() {
      this.fetchData()
    }

    fetchData() {
      RNCalendarEvents
        .fetchAllEvents(
          '2016-01-01T00:00:00.000Z', 
          '2016-12-30T23:00:00.000Z', 
          function(events) { this.setState({cEvents: events}) }.bind(this)
        )
    } 
```

and the cEvents is always null, I can only see it when I change the setState to console.log

**Comment by wmcmahan** [comment] 2016-03-07 14:29
Try using an arrow function to access _this_ object.
```
fetchData() {
      RNCalendarEvents
        .fetchAllEvents(
          '2016-01-01T00:00:00.000Z', 
          '2016-12-30T23:00:00.000Z', 
          events => this.setState({cEvents: events})
        )
    } 
```

**Comment by wmcmahan** [comment] 2016-03-07 16:18
Closing since this as original issue of fetching events seems to be ok.

**Closed by wmcmahan** 2016-03-07 16:18 UTC
